import ControleLivros from '@/classes/controle/ControleLivros';
import { Livro } from '@/classes/modelo/Livro';
import { LinhaLivro } from '@/componentes/LinhaLivro';
import { Menu } from '@/componentes/Menu';
import type{ NextPage } from 'next';
import Head from 'next/head';
import React, { useState, useEffect } from 'react';
import styles from '../styles/Home.module.css'

const LivroLista:NextPage = () => { 
    const [livros, setLivros] = useState(Array<Livro>);
    const [carregado, setCarregado] = useState(Boolean);

    const controleLivro = new ControleLivros()

    const getLivros = () => {
        controleLivro.obterLivros()
            .then(res => {
                setLivros(res);
            });
    };

    useEffect(() => {
        getLivros()
        setCarregado(true);
    }, [carregado]);

    const excluir = (codigo:string) => {
        controleLivro.excluir(codigo)
            .then( res => setCarregado(false) );
    };

    return (
        <div className='styles.container'>
            <Head>
                <title>Loja Next</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Menu/>
            <main className={styles.main}>
                <div className='container'>
                    <h1 className='text-center'>Catálogo de Livros</h1>
                    <table className='table table-dark table-hover'>
                    <thead>
                        <tr>
                            <td>Titulo</td>
                            <td>Resumo</td>
                            <td>Editora</td>
                            <td>Autores</td>
                        </tr>
                    </thead>
                    <tbody>
                        { livros && livros.map( (livro, index) => (
                            <LinhaLivro livro={livro} excluir={() => excluir(livro.codigo)} key={index}/>
                        ))}
                    </tbody>
                    </table>
                </div>
            </main>
        </div>
    );
};

export default LivroLista;